### ISSUE TITLE
Error when setup

### ISSUE THREAD

**Issue by Codexplay1** [ad4mny/devdcrs#1]
I want to connect it with xampp. AN UNCAUGHT EXCEPTION WAS ENCOUNTERED.
(I have created database with the .sql file.)

**Comment by ad4mny** [comment]
please elaborate your issues as i could not recreate one

**Comment by bsl-molnar** [comment]
Good afternoon,.  (sorry for being off topic)
Perhaps you have a demo?

**Comment by ad4mny** [comment]
here is a working demo
https://rushrepairpc.000webhostapp.com/
use staff as
user: sarah
pass: sarah123

for rider and customer, can register account yourself.
